export const countries = [
  'Ghana',
  'Armenia',
  'Saint Lucia',
  'Republic of Korea',
  'Sierra Leone',
  'Slovenia',
  'Lithuania',
  'Central African Republic',
  'United Kingdom',
  'Algeria',
  'Lesotho',
  'Sao Tome and Principe',
  'Brunei Darussalam',
  'Netherlands',
  'Indonesia',
  'Cocos (Keeling) Islands',
  'Aruba',
  'Egypt',
  'Ethiopia',
  'Marshall Islands',
  'Spain',
  'Montserrat',
  'Estonia',
  'Brazil',
  'Colombia',
  'Djibouti',
  'Cyprus',
  'Morocco',
  'Israel',
  'Ireland',
  'Liechtenstein',
  'Cape Verde',
  'Senegal',
  'Haiti',
  'Albania',
  'Gibraltar',
  'Cuba',
  'Anguilla',
  "Lao People's Democratic Republic",
  'Kuwait',
  'Saint Pierre and Miquelon',
  'Kiribati',
  'Japan',
  'Bolivia',
  'Swaziland',
  'Sudan',
  'United States of America'
]

export default countries